server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: sonalsisodia
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

